src/Entity/Recipes.php
<?php

namespace App\Entity;

use App\Repository\RecipesRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: RecipesRepository::class)]
class Recipes
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $name = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $text = null;

    #[ORM\Column]
    private ?int $duration = null;

    #[ORM\Column]
    private ?int $people_count = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $photo = null;

    /**
     * @var Collection<int, Comments>
     */
    #[ORM\OneToMany(targetEntity: Comments::class, mappedBy: 'recipeID')]
    private Collection $comments;


    public function __construct()
    {
        $this->comments = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): static
    {
        $this->name = $name;

        return $this;
    }

    public function getText(): ?string
    {
        return $this->text;
    }

    public function setText(string $text): static
    {
        $this->text = $text;

        return $this;
    }

    public function getDuration(): ?int
    {
        return $this->duration;
    }

    public function setDuration(int $duration): static
    {
        $this->duration = $duration;

        return $this;
    }

    public function getPeopleCount(): ?int
    {
        return $this->people_count;
    }

    public function setPeopleCount(int $people_count): static
    {
        $this->people_count = $people_count;

        return $this;
    }

    public function getPhoto(): ?string
    {
        return $this->photo;
    }

    public function setPhoto(?string $photo): static
    {
        $this->photo = $photo;

        return $this;
    }

    /**
     * @return Collection<int, Comments>
     */
    public function getComments(): Collection
    {
        return $this->comments;
    }

    public function addComment(Comments $comment): static
    {
        if (!$this->comments->contains($comment)) {
            $this->comments->add($comment);
            $comment->setRecipeID($this);
        }

        return $this;
    }

    public function removeComment(Comments $comment): static
    {
        if ($this->comments->removeElement($comment)) {
            // set the owning side to null (unless already changed)
            if ($comment->getRecipeID() === $this) {
                $comment->setRecipeID(null);
            }
        }

        return $this;
    }


}

src/Form/RecipesType.php
<?php

namespace App\Form;

use App\Entity\Recipes;
use App\Entity\Ingredients;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;

class RecipesType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('name')
            ->add('text')
            ->add('duration')
            ->add('people_count')
            ->add('photo')
            ->add('ingredients', EntityType::class, [
                'class' => Ingredients::class,
                'choice_label' => 'name',
                'multiple' => true,
                'expanded' => true, 
                'label' => 'Select Ingredients',
                'mapped' => false,
            ]);
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Recipes::class,
        ]);
    }
}

src/Controller/RecipesController.php
<?php

namespace App\Controller;

use App\Entity\Recipes;
use App\Form\RecipesType;
use App\Repository\RecipesRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;

#[Route('/recipes')]
final class RecipesController extends AbstractController
{
    #[Route(name: 'app_recipes_index', methods: ['GET'])]
    public function index(RecipesRepository $recipesRepository): Response
    {
        return $this->render('recipes/index.html.twig', [
            'recipes' => $recipesRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_recipes_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $recipe = new Recipes();

        $form = $this->createForm(RecipesType::class, $recipe);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($recipe);
            $entityManager->flush();

            $ingredients_list = '';
            $ingredient_details = $form["ingredients"]->getData();

            var_dump($ingredient_details);
            die();

            return $this->redirectToRoute('app_recipes_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('recipes/new.html.twig', [
            'recipe' => $recipe,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_recipes_show', methods: ['GET'])]
    public function show(Recipes $recipe): Response
    {
        return $this->render('recipes/show.html.twig', [
            'recipe' => $recipe,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_recipes_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Recipes $recipe, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(RecipesType::class, $recipe);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('app_recipes_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('recipes/edit.html.twig', [
            'recipe' => $recipe,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_recipes_delete', methods: ['POST'])]
    public function delete(Request $request, Recipes $recipe, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$recipe->getId(), $request->getPayload()->getString('_token'))) {
            $entityManager->remove($recipe);
            $entityManager->flush();
        }

        return $this->redirectToRoute('app_recipes_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/recipes/_delete_form.html.twig
<form method="post" action="{{ path('app_recipes_delete', {'id': recipe.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ recipe.id) }}">
    <button class="btn">Delete</button>
</form>

templates/recipes/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Recipes{% endblock %}

{% block body %}
    <h1>Edit Recipes</h1>

    {{ include('recipes/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_recipes_index') }}">back to list</a>

    {{ include('recipes/_delete_form.html.twig') }}
{% endblock %}

templates/recipes/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Recipes index{% endblock %}

{% block body %}
    <h1>All Recipes</h1>
    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Name</th>
                <th>Text</th>
                <th>Duration</th>
                <th>People_count</th>
                <th>Photo</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for recipe in recipes %}
            <tr>
                <td>{{ recipe.id }}</td>
                <td>{{ recipe.name }}</td>
                <td>{{ recipe.text }}</td>
                <td>{{ recipe.duration }}</td>
                <td>{{ recipe.peopleCount }}</td>
                <td>{{ recipe.photo }}</td>
                <td>
                    <a href="{{ path('app_recipes_show', {'id': recipe.id}) }}">show</a>
                    <a href="{{ path('app_recipes_edit', {'id': recipe.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="7">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('app_recipes_new') }}">Create a new recipe!</a>
{% endblock %}

templates/recipes/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Recipes{% endblock %}

{% block body %}
    <h1>Create new Recipes</h1>

    {{ include('recipes/_form.html.twig') }}

    <a href="{{ path('app_recipes_index') }}">back to list</a>
{% endblock %}

templates/recipes/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Recipes{% endblock %}

{% block body %}
    <h1>Recipes</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ recipe.id }}</td>
            </tr>
            <tr>
                <th>Name</th>
                <td>{{ recipe.name }}</td>
            </tr>
            <tr>
                <th>Text</th>
                <td>{{ recipe.text }}</td>
            </tr>
            <tr>
                <th>Duration</th>
                <td>{{ recipe.duration }}</td>
            </tr>
            <tr>
                <th>People_count</th>
                <td>{{ recipe.peopleCount }}</td>
            </tr>
            <tr>
                <th>Photo</th>
                <td>{{ recipe.photo }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_recipes_index') }}">back to list</a>

    <a href="{{ path('app_recipes_edit', {'id': recipe.id}) }}">edit</a>

    {{ include('recipes/_delete_form.html.twig') }}
{% endblock %}